import pandas as pd
import numpy as np


def generate_summary_stats(data, cont_cols, cat_cols, group_by_col=None):
    """
    Calculates raw summary statistics for continuous and categorical variables.
    Generates an 'Overall' summary, and optionally summaries grouped by a specific column.
    """
    all_results = {}

    def Q1(x):
        return x.quantile(0.25)

    def Q3(x):
        return x.quantile(0.75)

    def missing(x):
        return x.isna().sum()

    def compute_stats(df):
        summary = {}

        # 1. Continuous Variables Summary
        if cont_cols:
            # We use .agg to calculate exactly what you requested
            cont_stats = (
                df[cont_cols]
                .agg(
                    [
                        "count",
                        "mean",
                        "std",
                        "min",
                        Q1,
                        "median",
                        Q3,
                        "max",
                        missing,
                    ]
                )
                .T
            )  # Transpose so variables are rows and stats are columns

            # Clean up the column names generated by the lambda functions
            cont_stats.rename(columns={"<lambda_0>": "Q1", "<lambda_1>": "Q3", "<lambda_2>": "Missing"}, inplace=True)

            # Round for cleaner viewing
            summary["Continuous"] = cont_stats.round(2)

        # 2. Categorical Variables Summary
        if cat_cols:
            cat_stats = {}
            for col in cat_cols:
                # Calculate counts and percentages, including NaNs
                counts = df[col].value_counts(dropna=False)
                percents = df[col].value_counts(normalize=True, dropna=False) * 100

                # Merge into a clean sub-table
                cat_df = pd.DataFrame({"Count": counts, "Percentage (%)": percents.round(1)})
                cat_stats[col] = cat_df

            summary["Categorical"] = cat_stats

        return summary

    # --- Step 1: Calculate OVERALL statistics ---
    all_results["Overall"] = compute_stats(data)

    # --- Step 2: Calculate GROUPED statistics ---
    if group_by_col and group_by_col in data.columns:
        grouped = data.groupby(group_by_col)
        for group_name, group_df in grouped:
            all_results[f"{group_by_col}: {group_name}"] = compute_stats(group_df)

    return all_results


def main(data_path, cont_cols, cat_cols):
    data = pd.read_excel(data_path)
    stats_dictionary = generate_summary_stats(data, cont_cols, cat_cols, group_by_col="Sex")

    # How to view the results:
    print("--- OVERALL CONTINUOUS STATS ---")
    print(stats_dictionary["Overall"]["Continuous"].to_markdown())

    print("\n--- OVERALL CATEGORICAL STATS (Neurol_cond) ---")
    print(stats_dictionary["Overall"]["Categorical"]["Neurol_cond"].to_markdown())

    print("\n--- CONTINUOUS STATS FOR MALES ---")
    print(stats_dictionary["Sex: M"]["Continuous"].to_markdown())
    print("\n--- CONTINUOUS STATS FOR WOMEN ---")
    print(stats_dictionary["Sex: F"]["Continuous"].to_markdown())


if __name__ == "__main__":
    # Assuming 'data' is your merged dataframe
    cont_cols = ["Age", "Height", "Weight"]
    cat_cols = ["Sex", "functional_level", "Neurol_cond"]

    data_path = "/Volumes/SP UFD U2/PhD/Stage Nantes/data/datasets/final/final_data_matrix_sessions_separated.xlsx"

    main(data_path, cont_cols, cat_cols)
